version: '3.6'
services:
  graphql_kotlin_mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    container_name: "graphql_kotlin_mysql"
    hostname: "graphql_kotlin_mysql"
    ports:
      - "3316:3306"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      TZ: Asia/Tokyo

  graphql_kotlin_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "graphql_kotlin_phpmyadmin"
    hostname: "graphql_kotlin_phpmyadmin"
    ports:
      - "55555:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: graphql_kotlin_mysql
      PMA_USER: root
      PMA_PORT: 3306
      PMA_PASSWORD: root_password
    links:
      - graphql_kotlin_mysql